/* Copyright (c) 2026 Bertrand Hurst. All rights reserved.
** Escapement - Lightweight Power-Aware Real-Time OS.
** Derived from prior work; see LICENSE and NOTICE at the root of this repository.
*/
/* File UARTSimpleEcho.c: Receives characters that are then forwarded back to the sender.
** This application requires no special setting other than setting the system clocks.
** To build this application:
**    (1) Run "Escapement Configurator tool" and load the configuration file EXP430FR5739.zot
**        to generate the assembly and header files, and to get assembler function
**        OSInitializeSystemClocks that configures the clocks as shown below:
**          - MCLK sourced from the DCO (DCOCLK) divided by 1;
**          - ACLK sourced from the DCO (DCOCLK) divided by 8;
**          - SMCLK sourced from the DCO (DCOCLK) divided by 8;
**          - DCO set for factory calibrated value of 8.00 MHz(DCORSEL = 0, DCOFSEL = 3).
**    (2) You can then run a hyperterminal on a PC and transmit characters that are echoed
**        back.
** Tested on "MSP-EXP430FR5739 - Experimenter Board".
** Version identifier: March 2012

#include "Escapement.h"
#include "Escapement_UART.h"

/* UART transmit FIFO buffer size definitions */
#define UART_TRANSMIT_FIFO_NB_NODE    1
#define UART_TRANSMIT_FIFO_NODE_SIZE  10

/* UART entries to the interrupt table generated by Escapement Configurator Tool */
#if defined(OS_IO_USCI_A0_RX) && defined(OS_IO_USCI_A0_RX)
   #define UART_RX_VECTOR OS_IO_USCI_A0_RX
   #define UART_TX_VECTOR OS_IO_USCI_A0_TX
#else
   #error UART RX and TX interrupt vectors are not defined correctly
#endif

static BOOL UARTUserReceiveInterruptHandler(UINT8 data);
static void InitializeUARTHardware(void);

int main(void)
{
  WDTCTL = WDTPW + WDTHOLD;  // Disable watchdog timer

  /* Set the system clock characteristics */
  OSInitializeSystemClocks();

  /* Initialize Escapement I/O UART drivers */
  OSInitTransmitUART(UART_TRANSMIT_FIFO_NB_NODE,UART_TRANSMIT_FIFO_NODE_SIZE,UART_TX_VECTOR);
  OSInitReceiveUART(UARTUserReceiveInterruptHandler,UART_RX_VECTOR);

  /* Initialize USART or USCI 0 hardware */
  InitializeUARTHardware();

  /* Start the OS so that it runs the idle task, which puts the processor to sleep when
  ** there are no interrupts. */
  return OSStartMultitasking(NULL,NULL);
} /* end of main */


/* InitializeUARTHardware: Initializes USCI 0 hardware. */
void InitializeUARTHardware(void)
{
  P2SEL1 |= BIT0 + BIT1;
  P2SEL0 &= ~(BIT0 + BIT1);
  UCA0CTL1 |= UCSWRST;       // Put state machine in reset
  UCA0CTL1 |= UCSSEL__SMCLK; // Select SMCLK (1 MHz) as clock source
  UCA0BR0 = 6;               // 9600 Baud -> UCBRx = 6, UCBRSx = 0x20, UCBRFx = 8,
  UCA0BR1 = 0;               // UCOS16 -> 1
  UCA0MCTLW |= 0x2081;
  UCA0CTL1 &= ~UCSWRST;      // Initialize USCI state machine
  UCA0IE |= UCRXIE;          // Enable USCI_A0 RX interrupt
} /* end of InitializeUARTHardware */


/* UARTUserReceiveInterruptHandler: This function is called every time a new byte is
** received, and it simply copies the byte into the output queue of the UART. */
BOOL UARTUserReceiveInterruptHandler(UINT8 data)
{
  UINT8 *tmp;
  tmp = (UINT8 *)OSGetFreeNodeUART(UART_TX_VECTOR);
  *tmp = data;
  OSEnqueueUART(tmp,1,UART_TX_VECTOR);
  return TRUE; // Re-enable receive UART interrupt
} /* end of UARTUserReceiveInterruptHandler */
