#!/usr/bin/env python3
# Copyright (c) 2026 Bertrand Hurst. Part of Escapement, distributed under the terms of
# LICENSE at the root of this repository.
#
"""Pad the RP2040's second stage of boot to 252 bytes, append its CRC32, and write it as
an assembly source of one section, .boot2, 256 bytes long.

    tools/rp2040_boot2.py BOOT2_BIN OUT_S

BOOT2_BIN is Escapement_Boot2.S assembled and stripped to its .boot2 (objcopy -O binary).
The bootrom checks the CRC32 of the first 252 bytes against the last 4, little-endian:
polynomial 0x04c11db7, neither input nor output reflected, initial value 0xffffffff, no
final XOR (RP2040 datasheet, 2.8.1.3.1). The Makefile of the Pico assembles OUT_S into
the object it links at the start of the flash (RP2040_FLASH.ld).
"""

import struct
import sys


def crc32(data):
    crc = 0xFFFFFFFF
    for byte in data:
        crc ^= byte << 24
        for _ in range(8):
            crc = (crc << 1) ^ 0x04C11DB7 if crc & 0x80000000 else crc << 1
            crc &= 0xFFFFFFFF
    return crc


def main():
    code = open(sys.argv[1], "rb").read()
    if len(code) > 252:
        sys.exit(f"{sys.argv[1]}: {len(code)} bytes, more than the 252 of a second stage")
    image = code + bytes(252 - len(code))
    image += struct.pack("<I", crc32(image))
    with open(sys.argv[2], "w") as out:
        out.write(f"/* Generated by tools/rp2040_boot2.py from {sys.argv[1]}. */\n")
        out.write('    .section .boot2, "ax"\n')
        for i in range(0, 256, 16):
            out.write("    .byte " + ", ".join(f"0x{b:02x}" for b in image[i:i + 16]) + "\n")


if __name__ == "__main__":
    main()
